name: Run on TAG
on:
  push:
    branches:
      - "main"
    tags:
      - "*"

jobs:
  tag_job:
    # this job will only run if the PR has been merged
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - run: |
          env
          echo REFS $GITHUB_SHA $GITHUB_REF 

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT

      - name: Get repo 
        uses: actions/checkout@v4

      - name: Check that commit in required branch
        run: |
          full_name=(git branch -a --contains ${{ github.sha }})
          branch=$(echo ${full_name##*/} | tr [:upper:] [:lower:])
          echo "branch=$branch"
